name: Check Linked Issues

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches-ignore:
      - "dependabot"
      - "releases"

jobs:
  check_pull_requests:
    runs-on: ubuntu-latest
    name: Check linked issues
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use the action
        uses: nearform/github-action-check-linked-issues@initial-implementation
        id: check-linked-issues
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the output
        run: echo "Has linked issues? ${{ steps.check-linked-issues.outputs.linked_issues_count }}"
