name: Release Hotfix

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string
        default: "0.0.1"
      environment:
        required: true
        default: "stg"
        type: choice
        options:
          - "stg"
          - "uat"
          - "prd"

env:
  HOTFIX_TAG: "v${{ inputs.tag }}-${{ inputs.environment }}"

run-name: "Release Hotfix - v${{ inputs.tag }}-${{ inputs.environment }}"

jobs:
  tag:
    name: Hotfix
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create User Input Tag - Will fail if existing used
        uses: actions/github-script@v6.3.3
        with:
          script: |
            const {HOTFIX_TAG} = process.env
            console.log(HOTFIX_TAG, '=========')
